<?php

namespace XeroPHP\Enums\Accounting\Organisation;

class OrganisationType
{
    const ORGANISATION_TYPE_COMPANY = 'COMPANY';

    const ORGANISATION_TYPE_CHARITY = 'CHARITY';

    const ORGANISATION_TYPE_CLUBSOCIETY = 'CLUBSOCIETY';

    const ORGANISATION_TYPE_PARTNERSHIP = 'PARTNERSHIP';

    const ORGANISATION_TYPE_PRACTICE = 'PRACTICE';

    const ORGANISATION_TYPE_PERSON = 'PERSON';

    const ORGANISATION_TYPE_SOLETRADER = 'SOLETRADER';

    const ORGANISATION_TYPE_TRUST = 'TRUST';
}