<?php

namespace XeroPHP\Models\Accounting;

class SalesTaxPeriod {

    const AUSTRALIUM_MONTHLY    = 'MONTHLY';
    const AUSTRALIUM_QUARTERLY1 = 'QUARTERLY1';
    const AUSTRALIUM_QUARTERLY2 = 'QUARTERLY2';
    const AUSTRALIUM_QUARTERLY3 = 'QUARTERLY3';
    const AUSTRALIUM_ANNUALLY   = 'ANNUALLY';

    const NEW_ZEALAND_ONEMONTHS = 'ONEMONTHS';
    const NEW_ZEALAND_TWOMONTHS = 'TWOMONTHS';
    const NEW_ZEALAND_SIXMONTHS = 'SIXMONTHS';

    const US_GLOBAL_1MONTHLY = '1MONTHLY';
    const US_GLOBAL_2MONTHLY = '2MONTHLY';
    const US_GLOBAL_3MONTHLY = '3MONTHLY';
    const US_GLOBAL_6MONTHLY = '6MONTHLY';
    const US_GLOBAL_ANNUALLY = 'ANNUALLY';

    const UNITED_KINGDOM_MONTHLY   = 'MONTHLY';
    const UNITED_KINGDOM_QUARTERLY = 'QUARTERLY';
    const UNITED_KINGDOM_YEARLY    = 'YEARLY';


}