<?php

namespace XeroPHP\Models\Accounting;

class TaxType {

    const AUSTRALIUM_TAX_TYPE        = 'TAX TYPE';
    const AUSTRALIUM_OUTPUT          = 'OUTPUT';
    const AUSTRALIUM_INPUT           = 'INPUT';
    const AUSTRALIUM_CAPEXINPUT      = 'CAPEXINPUT';
    const AUSTRALIUM_EXEMPTEXPORT    = 'EXEMPTEXPORT';
    const AUSTRALIUM_EXEMPTEXPENSES  = 'EXEMPTEXPENSES';
    const AUSTRALIUM_EXEMPTCAPITAL   = 'EXEMPTCAPITAL';
    const AUSTRALIUM_EXEMPTOUTPUT    = 'EXEMPTOUTPUT';
    const AUSTRALIUM_INPUTTAXED      = 'INPUTTAXED';
    const AUSTRALIUM_BASEXCLUDED     = 'BASEXCLUDED';
    const AUSTRALIUM_GSTONCAPIMPORTS = 'GSTONCAPIMPORTS';
    const AUSTRALIUM_GSTONIMPORTS    = 'GSTONIMPORTS';

    const GLOBAL_TAX_TYPE     = 'TAX TYPE';
    const GLOBAL_INPUT        = 'INPUT';
    const GLOBAL_NONE         = 'NONE';
    const GLOBAL_OUTPUT       = 'OUTPUT';
    const GLOBAL_GSTONIMPORTS = 'GSTONIMPORTS';

    const NEW_ZEALAND_TAX_TYPE     = 'TAX TYPE';
    const NEW_ZEALAND_INPUT2       = 'INPUT2';
    const NEW_ZEALAND_NONE         = 'NONE';
    const NEW_ZEALAND_ZERORATED    = 'ZERORATED';
    const NEW_ZEALAND_OUTPUT2      = 'OUTPUT2';
    const NEW_ZEALAND_GSTONIMPORTS = 'GSTONIMPORTS';

    const UNITED_KINGDOM_TAX_TYPE           = 'TAX TYPE';
    const UNITED_KINGDOM_CAPEXINPUT         = 'CAPEXINPUT';
    const UNITED_KINGDOM_CAPEXINPUT2        = 'CAPEXINPUT2';
    const UNITED_KINGDOM_CAPEXOUTPUT        = 'CAPEXOUTPUT';
    const UNITED_KINGDOM_CAPEXOUTPUT2       = 'CAPEXOUTPUT2';
    const UNITED_KINGDOM_CAPEXSRINPUT       = 'CAPEXSRINPUT';
    const UNITED_KINGDOM_CAPEXSROUTPUT      = 'CAPEXSROUTPUT';
    const UNITED_KINGDOM_ECZRINPUT          = 'ECZRINPUT';
    const UNITED_KINGDOM_ECZROUTPUT         = 'ECZROUTPUT';
    const UNITED_KINGDOM_ECZROUTPUTSERVICES = 'ECZROUTPUTSERVICES';
    const UNITED_KINGDOM_EXEMPTINPUT        = 'EXEMPTINPUT';
    const UNITED_KINGDOM_EXEMPTOUTPUT       = 'EXEMPTOUTPUT';
    const UNITED_KINGDOM_GSTONIMPORTS       = 'GSTONIMPORTS';
    const UNITED_KINGDOM_INPUT2             = 'INPUT2';
    const UNITED_KINGDOM_NONE               = 'NONE';
    const UNITED_KINGDOM_OUTPUT2            = 'OUTPUT2';
    const UNITED_KINGDOM_RRINPUT            = 'RRINPUT';
    const UNITED_KINGDOM_RROUTPUT           = 'RROUTPUT';
    const UNITED_KINGDOM_SRINPUT            = 'SRINPUT';
    const UNITED_KINGDOM_SROUTPUT           = 'SROUTPUT';
    const UNITED_KINGDOM_ZERORATEDINPUT     = 'ZERORATEDINPUT';
    const UNITED_KINGDOM_ZERORATEDOUTPUT    = 'ZERORATEDOUTPUT';

    const UNITED_STATE_TAX_TYPE     = 'TAX TYPE';
    const UNITED_STATE_INPUT        = 'INPUT';
    const UNITED_STATE_NONE         = 'NONE';
    const UNITED_STATE_OUTPUT       = 'OUTPUT';
    const UNITED_STATE_GSTONIMPORTS = 'GSTONIMPORTS';


}