<?php

namespace XeroPHP\Models\Accounting;

class UserRole
{
    const XERO_USER_ROLE_READONLY = 'READONLY';

    const XERO_USER_ROLE_INVOICEONLY = 'INVOICEONLY';

    const XERO_USER_ROLE_STANDARD = 'STANDARD';

    const XERO_USER_ROLE_FINANCIALADVISER = 'FINANCIALADVISER';

    const XERO_USER_ROLE_MANAGEDCLIENT = 'MANAGEDCLIENT';

    const XERO_USER_ROLE_CASHBOOKCLIENT = 'CASHBOOKCLIENT';
}
