<?php

namespace XeroPHP\Models\Files;

class ObjectType
{
    const OBJECT_TYPE_ACCOUNT = 'ACCOUNT';

    const OBJECT_TYPE_ACCPAY = 'ACCPAY';

    const OBJECT_TYPE_ACCPAYCREDIT = 'ACCPAYCREDIT';

    const OBJECT_TYPE_ACCPAYPAYMENT = 'ACCPAYPAYMENT';

    const OBJECT_TYPE_ACCREC = 'ACCREC';

    const OBJECT_TYPE_ACCRECCREDIT = 'ACCRECCREDIT';

    const OBJECT_TYPE_ACCRECPAYMENT = 'ACCRECPAYMENT';

    const OBJECT_TYPE_ADJUSTMENT = 'ADJUSTMENT';

    const OBJECT_TYPE_APCREDITPAYMENT = 'APCREDITPAYMENT';

    const OBJECT_TYPE_APOVERPAYMENT = 'APOVERPAYMENT';

    const OBJECT_TYPE_APOVERPAYMENTPAYMENT = 'APOVERPAYMENTPAYMENT';

    const OBJECT_TYPE_APOVERPAYMENTSOURCEPAYMENT = 'APOVERPAYMENTSOURCEPAYMENT';

    const OBJECT_TYPE_APPREPAYMENT = 'APPREPAYMENT';

    const OBJECT_TYPE_APPREPAYMENTPAYMENT = 'APPREPAYMENTPAYMENT';

    const OBJECT_TYPE_APPREPAYMENTSOURCEPAYMENT = 'APPREPAYMENTSOURCEPAYMENT';

    const OBJECT_TYPE_ARCREDITPAYMENT = 'ARCREDITPAYMENT';

    const OBJECT_TYPE_AROVERPAYMENT = 'AROVERPAYMENT';

    const OBJECT_TYPE_AROVERPAYMENTPAYMENT = 'AROVERPAYMENTPAYMENT';

    const OBJECT_TYPE_AROVERPAYMENTSOURCEPAYMENT = 'AROVERPAYMENTSOURCEPAYMENT';

    const OBJECT_TYPE_ARPREPAYMENT = 'ARPREPAYMENT';

    const OBJECT_TYPE_ARPREPAYMENTPAYMENT = 'ARPREPAYMENTPAYMENT';

    const OBJECT_TYPE_ARPREPAYMENTSOURCEPAYMENT = 'ARPREPAYMENTSOURCEPAYMENT';

    const OBJECT_TYPE_CASHPAID = 'CASHPAID';

    const OBJECT_TYPE_CASHREC = 'CASHREC';

    const OBJECT_TYPE_CONTACT = 'CONTACT';

    const OBJECT_TYPE_EXPPAYMENT = 'EXPPAYMENT';

    const OBJECT_TYPE_FIXEDASSET = 'FIXEDASSET';

    const OBJECT_TYPE_MANUALJOURNAL = 'MANUALJOURNAL';

    const OBJECT_TYPE_PAYRUN = 'PAYRUN';

    const OBJECT_TYPE_PRICELISTITEM = 'PRICELISTITEM';

    const OBJECT_TYPE_PURCHASEORDER = 'PURCHASEORDER';

    const OBJECT_TYPE_RECEIPT = 'RECEIPT';

    const OBJECT_TYPE_TRANSFER = 'TRANSFER';
}
