<?php

namespace XeroPHP\Enums\PayrollAU\PayTemplates;

class EarningsType
{
    const ALLOWANCE = 'ALLOWANCE';

    const BACKPAY = 'BACKPAY';

    const COMMISSION = 'COMMISSION';

    const ORDINARYTIMEEARNINGS = 'ORDINARYTIMEEARNINGS';

    const OVERTIMEEARNINGS = 'OVERTIMEEARNINGS';

    const BONUSESANDCOMISSIONS = 'BONUSESANDCOMISSIONS';

    const LUMPSUMW = 'LUMPSUMW';

    const DIRECTORSFEES = 'DIRECTORSFEES';

    const PAIDPARENTALLEAVE = 'PAIDPARENTALLEAVE';

    const WORKERSCOMPENSATION = 'WORKERSCOMPENSATION';

}