<?php

namespace XeroPHP\Models\Assets;

class Overview
{
    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__DRAFT = 'Draft';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__REGISTERED = 'Registered';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__DISPOSED = 'Disposed';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__NODEPRECIATION = 'NoDepreciation';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__STRAIGHTLINE = 'StraightLine';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__DIMINISHINGVALUE100 = 'DiminishingValue100';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__DIMINISHINGVALUE150 = 'DiminishingValue150';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__DIMINISHINGVALUE200 = 'DiminishingValue200';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__FULLDEPRECIATION = 'FullDepreciation';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__RATE = 'Rate';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__LIFE = 'Life';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__NONE = 'None';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__ACTUALDAYS = 'ActualDays';

    const BELOW_IS_A_DETAILED_LIST_OF_ALL_THE_TYPES_AND_FOR_THE_ASSETS_API__FULLMONTH = 'FullMonth';
}
